[project]
name = "pima"
version = "0.1.0"
description = "Profit Tracker for Independent Shop Owners"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "streamlit>=1.49.1",
    "supabase>=2.19.0",
]
